### PR TITLE
[Code Quality] Upgrade Project

### PR DESCRIPTION
**Pull request by Panthr75**
Changes:
- Upgrades `LethalExpansion` to use `.netstandard 2.1`
- Changes dll references to be resolved via `Paths.props` and `Dependencies.props`

Specifically for @HolographicWings: here is the content to go into `Paths.props` to make it work as before:
```xml
<Project>
  <PropertyGroup>
    <GameAssembliesPath>C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data/Managed</GameAssembliesPath>
    <BepInExCorePath>C:/Users/Holog/AppData/Roaming/r2modmanPlus-local/LethalCompany/profiles/Default/BepInEx/core</BepInExCorePath>
    <LethalSDKPath>D:/Users/Holog/Documents/GitHub/LethalSDK/LethalSDK/bin/$(Configuration)/LethalSDK.dll</LethalSDKPath>
    <MoreCompanyPath>C:/Users/Holog/AppData/Roaming/r2modmanPlus-local/LethalCompany/profiles/Default/BepInEx/plugins/notnotnotswipez-MoreCompany/MoreCompany.dll</MoreCompanyPath>
  </PropertyGroup>
</Project>
```

### CODE REVIEW

**Comment by HolographicWings** [comment]
Why ?

**Comment by Panthr75** [comment]
Its far more maintainable for other contributors, as they don't have to replace all of your references with their own. They just setup a `Paths.props` file detailed from `CONTRIBUTING.md` and they are good to go.

As for the `.netstandard 2.1` upgrade, all mods should be targeting it as it's best practice.

**Comment by HolographicWings** [comment]
I wanted .net core originally
Why 2.1 must be targeted ? Except or because it's the version that the game targets

**Comment by Panthr75** [comment]
Yes. 2.1 is what the game and Unity targets

**Comment by Panthr75** [comment]
Any update on this?

**Comment by HolographicWings** [comment]
> Any update on this?

not yet, i'll look at it nextly

**Comment by Panthr75** [comment]
Ok as it turns out, the `PostBuildEvent` that copies the dll into that `Build` directory does not work.

**Comment by HolographicWings** [comment]
> Ok as it turns out, the `PostBuildEvent` that copies the dll into that `Build` directory does not work.

It work on my side

**Comment by HolographicWings** [comment]
> Ok as it turns out, the `PostBuildEvent` that copies the dll into that `Build` directory does not work.

It work on my side
For now I leave like that
If I begin to work with others peoples I may accept this PR
But not for now

**Comment by Panthr75** [comment]
As a result I will hold off on my other pull request then, as it was focused on improving code quality.

**Comment by HolographicWings** [comment]
> As a result I will hold off on my other pull request then, as it was focused on improving code quality.

no problem
i'm looking for active collaborators if you want to help more directly
i did an overdose in december, alone it's exhausting x)

**Comment by Panthr75** [comment]
Yeah I was waiting for the pr to be merged as we have access to new csharp language features that will make the code a lot nicer to work with

**Comment by HolographicWings** [comment]
> Yeah I was waiting for the pr to be merged as we have access to new csharp language features that will make the code a lot nicer to work with

I mean to add you as direct collaborator instead of making PRs

**Review by BuffMage — APPROVED** [review]
Everything seems to work nicely with this, makes it much easier to contribute!

**Pull request merged**
